name: Estichara
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+3

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  fluttertoast: ^8.2.2
  firebase_analytics: ^10.4.4
  firebase_storage: ^11.2.5
  firebase_performance: ^0.9.2+5
  introduction_screen: ^3.1.11
  flutter_onboarding_slider: ^1.0.9
  shared_preferences: ^2.2.0
  smooth_page_indicator: ^1.1.0
  email_validator: ^2.1.17
  pin_code_fields: ^8.0.1
  intl_phone_number_input: ^0.7.3+1
  persistent_bottom_nav_bar: ^5.0.2
  internet_connection_checker: ^1.0.0+1
  phone_number: ^2.0.1
  libphonenumber: ^2.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^5.1.0
  step_progress_indicator: ^1.0.2
  cloud_firestore: ^4.8.4
  firebase_crashlytics: ^3.3.5
  syncfusion_flutter_charts: ^22.2.9
  cupertino_icons: ^1.0.2
  connectivity_plus: ^4.0.2
  firebase_messaging: ^14.6.7
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.3.2
  google_mobile_ads: ^3.0.0
  web_socket_channel: ^2.4.0
  permission_handler: ^10.4.3
  fl_chart: ^0.63.0


flutter_native_splash:
  color: "#FF9800"
  image: img/chart.jpg
  android_disable_fullscreen: true
  android_12: 
    image: img/chart.jpg
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

  assets:
    - img/
  #   - images/a_dot_ham.jpeg





  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
